version: '3.8'

services:
  db:
    build:
      image: FROM postgres:12-alpine
    ports:
      - "5433:5432"
    image: 'db-image'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=backend_db
    volumes:
      - "db-data:/var/lib/postgresql/data"

  backend:
    build:
      context: ./
      dockerfile: Dockerfile-backend-build
    environment:
      - PORT=8080
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/backend_db
    image: 'backend-image'
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  db-data: