FROM adoptopenjdk/openjdk11:jdk-11.0.5_10-alpine as builder
RUN apk add git \
        && git clone https://github.com/alexmeh96/backend.git
WORKDIR /backend
RUN ./mvnw -Pprod clean install -DskipTests

FROM adoptopenjdk/openjdk11:alpine-jre
WORKDIR /app
COPY --from=builder /backend/target/*jar app.jar
ENTRYPOINT ["java","-jar", "app.jar"]