version: '3.8'

services:
  db:
    image: postgres:12-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=backend_db
    volumes:
      - "db-data:/var/lib/postgresql/data"

  backend:
    image: mehcoder/backend
    environment:
      - PORT=8080
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/backend_db
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  db-data: